CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID BIGINT NOT NULL,
    STORE_ID BIGINT NOT NULL,
    TOTAL_PRICE INT NOT NULL,
    ORDER_STATUS VARCHAR(50) NOT NULL,
    REG_DATE TIMESTAMP NOT NULL,
    MOD_DATE TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS ORDER_ITEM (
    ORDER_ITEM_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID BIGINT NOT NULL,
    ITEM_ID BIGINT NOT NULL,
    ITEM_PRICE BIGINT NOT NULL,
    ITEM_NAME VARCHAR(100) NOT NULL,
    ITEM_QUANTITY INT NOT NULL,
    ITEM_TOTAL_PRICE INT NOT NULL,
    REG_DATE TIMESTAMP NOT NULL,
    MOD_DATE TIMESTAMP NOT NULL
);
--
CREATE TABLE IF NOT EXISTS ORDER_EVENT (
    ORDER_EVENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    EVENT_UUID VARCHAR(100) NOT NULL,
    ORDER_ID BIGINT NOT NULL,
    REG_DATE TIMESTAMP NOT NULL,
    MOD_DATE TIMESTAMP NOT NULL
);